databases:
  - name: Nutrim
    databaseName: nutrim
    user: mysite
    plan: starter

services:
  - type: web
    name: mysite
    runtime: ruby
    plan: starter
    buildCommand: "./bin/render-build.sh"
    preDeployCommand: "bundle exec rails db:migrate" # preDeployCommand only available on paid instance types
    startCommand: "bundle exec rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: nutrim
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2 # sensible default